name: send_mail
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:  
      - name: Send mailer
        uses: devellany/send-mail@v1.0.2
        with:
          # Enter SMTP host.
          host: smtp.gmail.com
          # Enter SMTP port. (defaults to 465)
          port: 465 # optional, default is 465
          # Enter SMTP host account.
          account: fullstackdeveloper.sunny@gmail.com
          # Enter SMTP host account password.
          password: "umjt fiyw vziy lmxo"
          # Enter sender name.
          sender: 'Sunny'
          # Enter sender mail.
          from: 'fullstackdeveloper.sunny@gmail.com'
          # Enter recipient emails and separated with 'comma'. (The prefix 'file://' if you want to read a file)
          to: 'himanshu.bvdu04@gmail.com'
          # Enter the subject of the mail. (The prefix 'file://' if you want to read a file)
          subject: "email from github"
          # Enter the body of the mail. (The prefix 'file://' if you want to read a file)
          body: "test email from github"
                
